name: resqnow
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  equatable: ^2.0.5
  http: ^1.2.1
  sliding_up_panel: ^2.0.0+1

  # --- Core Utilities ---
  provider: ^6.1.2
  go_router: ^16.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  permission_handler: ^12.0.1
  dropdown_search: ^5.0.6
  sqflite: ^2.4.2
  path: ^1.8.3

  # --- Firebase ---
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  cloud_functions: ^5.0.4
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.2.10
  google_sign_in: ^6.2.1

  # --- UI & Animations ---
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  cupertino_icons: ^1.0.8
  dash_chat_2: ^0.0.21
  timeago: ^3.6.0

  # --- Device Features ---
  flutter_phone_direct_caller: ^2.1.1
  image_picker: ^1.1.1
  crop_your_image: ^1.0.1
  path_provider: ^2.1.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  google_maps_flutter: ^2.5.3
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.20
  youtube_player_flutter: ^9.1.2
  flutter_inappwebview: ^6.0.0
  cached_network_image: ^3.2.3
  google_mlkit_image_labeling: ^0.11.0
  flutter_tts: ^3.8.0
  audioplayers: ^5.2.1
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"

  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  # assets:
  #   - lib/assets/animation/success_check.json
  #   - lib/assets/images/logo.png
  #   - lib/assets/images/icons/
  #   - lib/assets/images/firstaid_images/
  #   - lib/assets/images/kits/
  #   - assets/sounds/beep.wav
  #   - assets/animation/Audio&Voice-A-002.json
  assets:
    - assets/animation/
    - assets/animation/Doctor, Medical, Surgeon, Healthcare Animation.json
    - lib/assets/animation/success_check.json
    - assets/sounds/beep.wav
    - assets/images/app_icon.png
    - assets/images/Screenshot 2026-02-23 221241.png
    - assets/images/Screenshot 2026-02-23 221303.png
    - assets/images/Screenshot 2026-02-23 221324.png
    - lib/assets/images/icons/
    - lib/assets/images/firstaid_images/
    - lib/assets/images/kits/
    - assets/data/districts_kerala.json
    - assets/data/cities_kerala.json
    - assets/data/states_india.json
    - assets/data/pin_palakkad.json

  # Uncomment and add your custom fonts when needed
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
